name: Automated Lighthouse Report

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  run-script-and-archive:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run main script
        run: node scripts/main.mjs

      - name: Archive artifacts
        if:always()
        uses: actions/upload-artifact@v4
        with:
          name: output-artifacts
          path: auto_*