name: Automated Lighthouse Report

on:
  workflow_run:
    workflows: ["Deploy Next.js site to pages"]  # Replace with the name of the triggering workflow (from its `name:` field)
    types:
      - completed

jobs:
  run-script-and-archive:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run main script
        run: node scripts/main.mjs

      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output-artifacts
          path: auto_*